#@url = https://8080-marcoweb-apiquiz20242-us2tnb4btx5.ws-us116.gitpod.io

@url = https://8080-francielimr-apiquiz2024-otbxsa9pyhq.ws-us116.gitpod.io

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBUEkgUXVpenplcyIsInN1YiI6ImFkbWluIiwiZXhwIjoxNzMwODQzNTkxfQ.XndpS-VmFxykb-BL-e1NdNGchxVrYii3_XJSopUSH_w

###
GET {{url}}/categorias
Authorization: Bearer {{token}}

###
GET {{url}}/categorias/10

###
POST {{url}}/categorias
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "Conhecimentos Gerais"
}

###
DELETE {{url}}/categorias/5

###
PUT {{url}}/categorias/10
Content-Type: application/json

{
    "nome": "Arquitetura de APIs  - Alterado"
}